const VERSION = "v6.9 Puter IA";
const STORE = { history: "alaya_v69_history", settings: "alaya_v69_settings", draft: "alaya_v69_draft" };
const $ = (s, root = document) => root.querySelector(s);
const $$ = (s, root = document) => [...root.querySelectorAll(s)];
const signs = ["Aries","Tauro","Géminis","Cáncer","Leo","Virgo","Libra","Escorpio","Sagitario","Capricornio","Acuario","Piscis"];
const glyph = {Aries:"♈",Tauro:"♉",Géminis:"♊",Cáncer:"♋",Leo:"♌",Virgo:"♍",Libra:"♎",Escorpio:"♏",Sagitario:"♐",Capricornio:"♑",Acuario:"♒",Piscis:"♓"};
const planets = { sol:"☉", luna:"☽", asc:"ASC", mercurio:"☿", venus:"♀", marte:"♂" };

function read(key, fallback){ try { return JSON.parse(localStorage.getItem(key)) ?? fallback; } catch { return fallback; } }
function write(key, value){ localStorage.setItem(key, JSON.stringify(value)); }
function toast(msg){ const t=document.createElement('div'); t.className='toast'; t.textContent=msg; document.body.append(t); setTimeout(()=>t.remove(),2600); }
function route(id){ $$('.screen').forEach(s=>s.classList.toggle('active',s.id===id)); $$('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===id)); location.hash=id; if(id==='historial') renderHistory(); if(id==='inicio') renderHome(); }
function setStep(n){ $$('.step-page').forEach(p=>p.classList.toggle('active',p.dataset.page===String(n))); $$('.dot').forEach(d=>d.classList.toggle('active',d.dataset.step===String(n))); }
function formData(){ return Object.fromEntries(new FormData($('#chartForm')).entries()); }
function requiredOk(){ const d=formData(); const missing=[]; if(!d.name?.trim()) missing.push('nombre'); if(!d.birthDate) missing.push('fecha'); if(!d.birthTime) missing.push('hora'); if(!d.city?.trim()) missing.push('ciudad'); if(!d.country?.trim()) missing.push('país'); if(missing.length){ toast('Falta: '+missing.join(', ')); return false;} return true; }
function hash(str){ let h=2166136261; for(let i=0;i<str.length;i++){ h^=str.charCodeAt(i); h=Math.imul(h,16777619);} return Math.abs(h); }
function dayOfYear(dateStr){ const d=new Date(dateStr+'T12:00:00'); const y=new Date(d.getFullYear(),0,0); return Math.floor((d-y)/86400000); }
function sunSign(dateStr){ const md=dateStr.slice(5); const ranges=[['Capricornio','01-20'],['Acuario','02-19'],['Piscis','03-21'],['Aries','04-20'],['Tauro','05-21'],['Géminis','06-21'],['Cáncer','07-23'],['Leo','08-23'],['Virgo','09-23'],['Libra','10-23'],['Escorpio','11-22'],['Sagitario','12-22'],['Capricornio','12-32']]; for(const [sign, end] of ranges){ if(md < end) return sign; } return 'Capricornio'; }
function simplePositions(d){ const seed=hash(`${d.name}|${d.birthDate}|${d.birthTime}|${d.city}|${d.country}`); const sol=sunSign(d.birthDate); const idx=signs.indexOf(sol); const [hh,mm]=(d.birthTime||'12:00').split(':').map(Number); const lunarIndex=(dayOfYear(d.birthDate)+seed)%12; const ascIndex=(Math.floor((hh*60+mm)/120)+idx+hash(d.city)%12)%12; const mercury=signs[(idx+11+(seed%3))%12]; const venus=signs[(idx+10+(seed%5))%12]; const mars=signs[(idx+2+(seed%6))%12]; return { sol, luna: signs[lunarIndex], asc: signs[ascIndex], mercurio: mercury, venus, marte: mars } }
function degreeFor(sign, key, seed){ const base=Math.max(0,signs.indexOf(sign))*30; return (base + (hash(`${key}|${seed}|${sign}`)%30)) % 360; }
function degreeLabel(deg){ const sign=signs[Math.floor((((deg%360)+360)%360)/30)]; const local=Math.round((((deg%30)+30)%30)); return `${local}° ${sign}`; }
function buildDegrees(final,d){ const seed=`${d.name}|${d.birthDate}|${d.birthTime}|${d.city}`; const out={}; Object.entries(final).forEach(([k,sign])=>out[k]=degreeFor(sign,k,seed)); return out; }
function elementFor(sign){ if(['Aries','Leo','Sagitario'].includes(sign)) return 'Fuego'; if(['Tauro','Virgo','Capricornio'].includes(sign)) return 'Tierra'; if(['Géminis','Libra','Acuario'].includes(sign)) return 'Aire'; return 'Agua'; }
function elementAdvice(el){ return {Fuego:'activar iniciativa sin quemarte',Tierra:'ordenar prioridades y sostener hábitos',Aire:'pensar claro y comunicar mejor',Agua:'escuchar emociones y cuidar vínculos'}[el]; }
function archetype(el, type){ if(type==='compatibilidad') return {Fuego:'Alianza valiente',Tierra:'Vínculo estable',Aire:'Conexión mental',Agua:'Puente emocional'}[el]; if(type==='hoy') return {Fuego:'Chispa del día',Tierra:'Raíz del día',Aire:'Brújula mental',Agua:'Marea interior'}[el]; return {Fuego:'La Iniciadora',Tierra:'La Guardiana',Aire:'La Mensajera',Agua:'La Sensible'}[el]; }
function parseAstro(text){ if(!text) return {}; const map={sol:['sol','sun','☉'],luna:['luna','moon','☽'],asc:['asc','ascendente','ac','ASC'],mercurio:['mercurio','mercury','☿'],venus:['venus','♀'],marte:['marte','mars','♂']}; const out={}; const lower=text.toLowerCase(); Object.entries(map).forEach(([k,keys])=>{ for(const key of keys){ const pos=lower.indexOf(key.toLowerCase()); if(pos>=0){ const slice=text.slice(pos,pos+80); const found=signs.find(s=>slice.toLowerCase().includes(s.toLowerCase())) || Object.entries(glyph).find(([s,g])=>slice.includes(g))?.[0]; if(found){ out[k]=found; break; } } } }); return out; }
function buildReading(d){ const pos=simplePositions(d); const astro=parseAstro(d.astroText||''); const final={...pos,...astro}; const degrees=buildDegrees(final,d); const dominant=elementFor(final.sol); const type=d.readingType||'natal'; const title= type==='hoy' ? `Energía de hoy para ${d.name}` : type==='compatibilidad' ? `Compatibilidad de ${d.name}${d.otherName?' y '+d.otherName:''}` : `Carta natal de ${d.name}`;
  const precision = Object.keys(astro).length ? 'Revisada con Astro.com manual' : (d.timeAccuracy==='alta'?'Base clara':'Base simbólica');
  const aura = 72 + (hash(title)%24);
  const message = type==='compatibilidad' ? `La clave está en ${elementAdvice(dominant)} dentro del vínculo.` : `Tu energía principal invita a ${elementAdvice(dominant)}.`;
  const sections = [
    {title:'Resumen claro', text:`${message} Sol en ${final.sol}, Luna en ${final.luna} y Ascendente en ${final.asc} crean una lectura centrada en ${dominant.toLowerCase()}.`},
    {title:'Personalidad', text:`El Sol en ${final.sol} marca la forma en que expresas identidad, impulso y dirección vital.`},
    {title:'Mundo emocional', text:`La Luna en ${final.luna} habla de cómo procesas emociones, seguridad y necesidades internas.`},
    {title:'Cómo te muestras', text:`El Ascendente en ${final.asc} describe la primera impresión, el ritmo externo y cómo empiezas las cosas.`},
    {title:'Plan útil', list:[`Activar: ${elementAdvice(dominant)}.`,`Soltar: exceso de ruido o exigencia.`,`Microacción: escribe una decisión pequeña que puedas hacer hoy.`]},
    {title:'Nota de precisión', text:`Esta versión usa cálculo simbólico/aproximado. Para una carta profesional exacta, pega posiciones revisadas manualmente desde Astro.com en el modo avanzado.`}
  ];
  if(type==='compatibilidad') sections.splice(4,0,{title:'Compatibilidad', text:`La relación se lee como un puente entre ritmos. La recomendación es hablar desde claridad, cuidar expectativas y convertir la diferencia en colaboración.`});
  return { id:'alaya-'+Date.now(), created:new Date().toISOString(), title, subtitle:`${d.city}, ${d.country} · ${d.birthDate} ${d.birthTime}`, data:d, positions:final, degrees, dominant, archetype:archetype(dominant,type), precision, aura, sections, aiInterpretation:'' };
}
function renderWheel(r){
  const keys=['sol','luna','asc','mercurio','venus','marte'];
  const signRing=signs.map((s,i)=>`<span class="zodiac-label" style="--a:${i*30+15}deg"><b>${glyph[s]}</b><small>${s.slice(0,3)}</small></span>`).join('');
  const houses=Array.from({length:12},(_,i)=>`<span class="house-line" style="--a:${i*30}deg"></span>`).join('');
  const items=keys.map(k=>{ const deg=r.degrees?.[k] ?? 0; const name={sol:'Sol',luna:'Luna',asc:'Asc',mercurio:'Mercurio',venus:'Venus',marte:'Marte'}[k]; return `<span class="planet" style="--a:${deg}deg" title="${name}: ${degreeLabel(deg)}"><b>${planets[k]}</b><small>${r.positions[k]||'—'}</small></span>`; }).join('');
  return `${houses}${signRing}<div class="wheel-core"><b>${glyph[r.positions.sol]||'✦'}</b><small>Sol en ${r.positions.sol}</small></div>${items}`;
}
function renderPositionPanel(r){
  const keys=[['sol','Sol',planets.sol],['luna','Luna',planets.luna],['asc','Ascendente',planets.asc],['mercurio','Mercurio',planets.mercurio],['venus','Venus',planets.venus],['marte','Marte',planets.marte]];
  return `<div class="position-title"><p class="eyebrow">Posiciones principales</p><h3>Mapa de la carta</h3><p>Estos son los puntos que ves colocados en la rueda.</p></div>` + keys.map(([k,name,sym])=>`<article class="position-card"><span>${sym}</span><div><b>${name}</b><small>${degreeLabel(r.degrees?.[k] ?? 0)}</small></div></article>`).join('') + `<div class="precision-note"><b>Precisión:</b> ${r.precision}. Para exactitud profesional, revisa con Astro.com y pega las posiciones en modo avanzado.</div>`;
}
function renderGenericGuide(r){
  return `<div class="guide-title"><p class="eyebrow">Guía rápida</p><h3>Cómo leer esta carta</h3><p>Esta explicación es genérica y aparece siempre bajo la rueda para que sepas qué estás mirando antes de pedir la interpretación IA.</p></div>
  <div class="guide-grid">
    <article><b>Rueda astral</b><span>Es el mapa circular de la carta. Divide la experiencia en signos, casas y posiciones planetarias.</span></article>
    <article><b>Casas</b><span>Son las 12 áreas de vida. Las líneas de la rueda marcan temas como identidad, vínculos, hogar, trabajo, relaciones y propósito.</span></article>
    <article><b>Ascendente</b><span>Es la puerta de entrada de la carta. Habla de cómo empiezas las cosas, cómo te muestras y cómo te perciben al principio.</span></article>
    <article><b>Sol</b><span>Representa identidad, dirección vital y energía central. En esta carta aparece en ${r.positions.sol}.</span></article>
    <article><b>Luna</b><span>Representa mundo emocional, necesidades internas y forma de sentir. En esta carta aparece en ${r.positions.luna}.</span></article>
    <article><b>Planetas</b><span>Cada símbolo señala una función: Mercurio comunica, Venus vincula, Marte activa. El signo muestra el estilo de esa energía.</span></article>
  </div>`;
}
function escapeHtml(str=''){ return String(str).replace(/[&<>"]/g, c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c])); }
function puterLoaded(){ return typeof window.puter !== 'undefined' && puter.auth && puter.ai; }
function puterSigned(){ try{ return puterLoaded() && puter.auth.isSignedIn(); } catch { return false; } }
async function updatePuterStatus(root=document){ const status=$('[data-field="puterStatus"]',root); if(!status) return; if(!puterLoaded()){ status.textContent='Puter no cargado'; status.className='ai-status warn'; return; } if(puterSigned()){ try{ const user=await puter.auth.getUser(); status.textContent=`Puter conectado${user?.username?' · '+user.username:''}`; status.className='ai-status ok'; } catch { status.textContent='Puter conectado'; status.className='ai-status ok'; } } else { status.textContent='Puter sin iniciar sesión'; status.className='ai-status warn'; } }
function aiPrompt(r){ return `Eres Alaya Astral IA. Redacta una interpretación astrológica clara, bonita y responsable en español. No hagas predicciones absolutas ni afirmes certezas científicas. Usa tono místico pero práctico.\n\nDatos de carta:\nNombre: ${r.data.name}\nTipo: ${r.data.readingType}\nFecha/hora/lugar: ${r.subtitle}\nSol: ${r.positions.sol} (${degreeLabel(r.degrees.sol)})\nLuna: ${r.positions.luna} (${degreeLabel(r.degrees.luna)})\nAscendente: ${r.positions.asc} (${degreeLabel(r.degrees.asc)})\nMercurio: ${r.positions.mercurio}\nVenus: ${r.positions.venus}\nMarte: ${r.positions.marte}\nElemento dominante: ${r.dominant}\nArquetipo: ${r.archetype}\nPrecisión: ${r.precision}\nIntención: ${r.data.intention || 'Sin intención escrita'}\n\nEstructura obligatoria:\n1. Resumen central\n2. Sol, Luna y Ascendente\n3. Casas y rueda astral explicadas de forma sencilla\n4. Talentos y retos\n5. Consejo práctico\n6. Afirmación final\n\nMáximo 900 palabras.`; }
function normalizeAI(res){ if(typeof res==='string') return res; if(res?.message?.content) return res.message.content; if(res?.content) return res.content; if(res?.text) return res.text; if(Array.isArray(res)) return res.map(normalizeAI).join('\n'); return String(res ?? 'Sin respuesta.'); }
async function signInPuter(root=document){ if(!puterLoaded()){ toast('Puter.js no se ha cargado. Revisa internet o publica la app en HTTPS.'); updatePuterStatus(root); return false; } try{ await puter.auth.signIn(); await updatePuterStatus(root); toast('Puter conectado'); return true; } catch(err){ toast('No se completó el inicio de sesión en Puter'); return false; } }
async function generateAIInterpretation(r, root){ const out=$('[data-field="aiOutput"]',root); if(!out) return; if(!puterLoaded()){ out.innerHTML='<b>Puter no está cargado.</b><br>Abre la app con internet. En algunos navegadores funciona mejor publicada en HTTPS.'; updatePuterStatus(root); return; } if(!puterSigned()){ out.innerHTML='<b>Primero inicia sesión o regístrate en Puter.</b><br>Pulsa el botón 1 y vuelve a generar la interpretación.'; await updatePuterStatus(root); return; } out.innerHTML='<div class="ai-loading">Generando interpretación IA con Puter…</div>'; try{ const res=await puter.ai.chat(aiPrompt(r), { model:'gpt-5-nano' }); const text=normalizeAI(res).trim(); r.aiInterpretation=text; out.innerHTML=`<div class="ai-text">${escapeHtml(text).replace(/\n/g,'<br>')}</div>`; const slot=$('#resultSlot'); if(slot) slot.dataset.reading=JSON.stringify(r); toast('Interpretación IA generada'); } catch(err){ out.innerHTML='<b>No se pudo generar la interpretación IA.</b><br>Comprueba que has iniciado sesión en Puter y que tienes conexión.'; }
}
function renderReading(r){ setStep(3); const tpl=$('#readingTemplate').content.cloneNode(true); $('[data-field="title"]',tpl).textContent=r.title; $('[data-field="subtitle"]',tpl).textContent=r.subtitle; $('[data-field="badges"]',tpl).innerHTML=[r.dominant,r.archetype,r.precision,`Aura ${r.aura}`].map(x=>`<span class="badge">${x}</span>`).join(''); $('[data-field="wheel"]',tpl).innerHTML=renderWheel(r); $('[data-field="positionPanel"]',tpl).innerHTML=renderPositionPanel(r); $('[data-field="genericGuide"]',tpl).innerHTML=renderGenericGuide(r); $('[data-field="sections"]',tpl).innerHTML=r.sections.map(s=>`<section class="result-section"><h3>${s.title}</h3>${s.text?`<p>${s.text}</p>`:''}${s.list?`<ul class="mini-list">${s.list.map(i=>`<li>${i}</li>`).join('')}</ul>`:''}</section>`).join(''); const slot=$('#resultSlot'); slot.innerHTML=''; slot.append(tpl); slot.dataset.reading=JSON.stringify(r); const article=slot.querySelector('.reading'); if(r.aiInterpretation){ $('[data-field="aiOutput"]',article).innerHTML=`<div class="ai-text">${escapeHtml(r.aiInterpretation).replace(/\n/g,'<br>')}</div>`; } $('[data-action="save"]',slot).onclick=()=>{ const latest=JSON.parse(slot.dataset.reading||JSON.stringify(r)); saveReading(latest); }; $('[data-action="focusWheel"]',slot).onclick=()=>slot.querySelector('.chart-hero').scrollIntoView({behavior:'smooth',block:'start'}); $('[data-action="pdf"]',slot).onclick=()=>window.print(); $('[data-action="copy"]',slot).onclick=()=>copyText(readingText(JSON.parse(slot.dataset.reading||JSON.stringify(r)))); $('[data-action="html"]',slot).onclick=()=>{ const latest=JSON.parse(slot.dataset.reading||JSON.stringify(r)); download(`alaya-carta-${latest.id}.html`,htmlDoc(latest),'text/html'); }; $('[data-action="puterLogin"]',slot).onclick=()=>signInPuter(article); $('[data-action="aiInterpret"]',slot).onclick=()=>generateAIInterpretation(JSON.parse(slot.dataset.reading||JSON.stringify(r)), article); updatePuterStatus(article); slot.scrollIntoView({behavior:'smooth',block:'start'}); }
function readingText(r){ const base=`${r.title}\n${r.subtitle}\n\n${r.sections.map(s=>`${s.title}\n${s.text||''}${s.list?'\n- '+s.list.join('\n- '):''}`).join('\n\n')}`; return r.aiInterpretation ? `${base}\n\nInterpretación IA Puter\n${r.aiInterpretation}` : base; }
function htmlDoc(r){ return `<!doctype html><html lang="es"><meta charset="utf-8"><title>${r.title}</title><style>body{font-family:system-ui;margin:0;background:#080412;color:#fff8ec}.wrap{max-width:900px;margin:auto;padding:42px}.card{border:1px solid rgba(255,255,255,.18);border-radius:28px;background:rgba(255,255,255,.07);padding:24px;margin:16px 0}h1{font-size:48px;line-height:1}small{opacity:.7}@media print{body{background:#fff;color:#111}.card{border-color:#ddd;background:#fff}}</style><main class="wrap"><small>Alaya Astral IA · ${VERSION}</small><h1>${r.title}</h1><p>${r.subtitle}</p><p><b>${r.dominant}</b> · ${r.archetype} · ${r.precision}</p><section class="card"><h2>Cómo leer la carta</h2><p>La rueda muestra signos, casas y planetas. El Ascendente es la puerta de entrada de la carta. El Sol habla de identidad, la Luna del mundo emocional y los planetas de funciones concretas.</p></section>${r.sections.map(s=>`<section class="card"><h2>${s.title}</h2><p>${s.text||''}</p>${s.list?`<ul>${s.list.map(i=>`<li>${i}</li>`).join('')}</ul>`:''}</section>`).join('')}${r.aiInterpretation?`<section class="card"><h2>Interpretación IA Puter</h2><p>${escapeHtml(r.aiInterpretation).replace(/\n/g,'<br>')}</p></section>`:''}</main>`; }
function download(name, content, type='application/json'){ const blob=new Blob([content],{type}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=name; a.click(); setTimeout(()=>URL.revokeObjectURL(a.href),1000); }
function saveReading(r){ const h=read(STORE.history,[]); const idx=h.findIndex(x=>x.id===r.id); if(idx>=0) h[idx]=r; else h.unshift(r); write(STORE.history,h); renderHome(); renderHistory(); toast('Carta guardada'); }
function renderHome(){ const h=read(STORE.history,[]); const last=h[0]; $('#lastCard').innerHTML = last ? `<p class="eyebrow">Última carta</p><h2>${last.title}</h2><p>${last.subtitle}</p><div class="badges"><span class="badge">${last.dominant}</span><span class="badge">Aura ${last.aura}</span>${last.aiInterpretation?'<span class="badge">IA Puter</span>':''}</div><button class="btn secondary small" id="openLast">Abrir</button>` : `<p class="eyebrow">Última carta</p><h2>Todavía no hay cartas</h2><p>Crea una carta para verla aquí y guardarla en el historial.</p>`; if($('#openLast')) $('#openLast').onclick=()=>{route('crear');renderReading(last)}; }
function renderHistory(){ const h=read(STORE.history,[]); $('#historyList').innerHTML = h.length ? h.map(r=>`<article class="history-item"><div><h3>${r.title}</h3><p>${new Date(r.created).toLocaleDateString()} · ${r.dominant} · Aura ${r.aura}${r.aiInterpretation?' · IA Puter':''}</p></div><div class="actions"><button class="btn secondary small" data-open="${r.id}">Abrir</button><button class="btn ghost small" data-delete="${r.id}">Borrar</button></div></article>`).join('') : `<div class="card" style="padding:24px">No hay cartas guardadas todavía.</div>`; $$('[data-open]').forEach(b=>b.onclick=()=>{ const r=read(STORE.history,[]).find(x=>x.id===b.dataset.open); route('crear'); renderReading(r); }); $$('[data-delete]').forEach(b=>b.onclick=()=>{ write(STORE.history, read(STORE.history,[]).filter(x=>x.id!==b.dataset.delete)); renderHistory(); renderHome(); toast('Carta borrada'); }); }
function copyText(t){ navigator.clipboard?.writeText(t).then(()=>toast('Copiado')).catch(()=>toast('No se pudo copiar')); }
function applySettings(){ const s=read(STORE.settings,{}); document.body.classList.toggle('comfort',!!s.comfort); document.body.classList.toggle('contrast',!!s.contrast); $('#comfortToggle').checked=!!s.comfort; $('#contrastToggle').checked=!!s.contrast; }
function saveDraft(){ write(STORE.draft, formData()); }
function loadDraft(){ const d=read(STORE.draft,null); if(!d) return; Object.entries(d).forEach(([k,v])=>{ const el=$(`[name="${k}"]`)||$('#'+k); if(el){ if(el.type==='radio'){ $$(`[name="${k}"]`).forEach(r=>r.checked=r.value===v); } else el.value=v; } }); updateChoices(); }
function updateChoices(){ $$('.choice').forEach(c=>c.classList.toggle('selected',$('input',c).checked)); const type=$('input[name="readingType"]:checked')?.value; $('#compatBox').classList.toggle('hidden',type!=='compatibilidad'); }
function createDemo(){ const demo={name:'Atenea',birthDate:'2008-07-21',birthTime:'12:30',city:'Barcelona',country:'España',timeAccuracy:'media',readingType:'natal',intention:'Quiero una lectura clara, bonita y fácil de entender.'}; Object.entries(demo).forEach(([k,v])=>{ const el=$(`[name="${k}"]`); if(el){ if(el.type==='radio') $$(`[name="${k}"]`).forEach(r=>r.checked=r.value===v); else el.value=v; } }); updateChoices(); route('crear'); const r=buildReading(demo); renderReading(r); saveReading(r); toast('Demo creada y guardada'); }
function bind(){ document.addEventListener('click',e=>{ const r=e.target.closest('[data-route]'); if(r){ e.preventDefault(); route(r.dataset.route); } const n=e.target.closest('[data-next]'); if(n){ if(n.dataset.next==='2' && !requiredOk()) return; setStep(n.dataset.next); } const s=e.target.closest('[data-step]'); if(s){ setStep(s.dataset.step); } }); $('#chartForm').addEventListener('submit',e=>{ e.preventDefault(); if(!requiredOk()) return; const d=formData(); saveDraft(); const r=buildReading(d); renderReading(r); }); $('#chartForm').addEventListener('input',()=>{ saveDraft(); updateChoices(); }); $('#demoBtn').onclick=createDemo; $('#clearHistoryBtn').onclick=()=>{ if(confirm('¿Borrar todas las cartas guardadas?')){ write(STORE.history,[]); renderHistory(); renderHome(); toast('Historial borrado'); } }; $('#exportBtn').onclick=()=>download('alaya-historial-v69.json',JSON.stringify(read(STORE.history,[]),null,2)); $('#importFile').onchange=e=>{ const f=e.target.files[0]; if(!f) return; const rd=new FileReader(); rd.onload=()=>{ try{ const arr=JSON.parse(rd.result); if(!Array.isArray(arr)) throw new Error('Formato inválido'); write(STORE.history,arr); renderHistory(); renderHome(); toast('Historial importado'); }catch{ toast('Archivo no válido'); } }; rd.readAsText(f); }; $('#comfortToggle').onchange=e=>{ const s=read(STORE.settings,{}); s.comfort=e.target.checked; write(STORE.settings,s); applySettings(); }; $('#contrastToggle').onchange=e=>{ const s=read(STORE.settings,{}); s.contrast=e.target.checked; write(STORE.settings,s); applySettings(); }; }
let deferredPrompt=null; window.addEventListener('beforeinstallprompt',e=>{ e.preventDefault(); deferredPrompt=e; $('#installBtn')?.classList.remove('hidden'); });
document.addEventListener('DOMContentLoaded',()=>{ bind(); loadDraft(); applySettings(); renderHome(); renderHistory(); updateChoices(); if(location.hash) route(location.hash.slice(1)); $('#installBtn').onclick=async()=>{ if(deferredPrompt){ deferredPrompt.prompt(); deferredPrompt=null; } }; if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{}); });
